steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - check_website
  - --source=.
  - --runtime=python310
  - --trigger-http
  - --allow-unauthenticated
  - --region=europe-west1
  - --entry-point=check_website
  - --service-account=service-account-v1@website-checker-v2.iam.gserviceaccount.com
